// Central mock data for Teacher Dashboard
export const STUDENTS = [
    {
        id: "s1",
        name: "Aarav Sharma",
        roll: "CSE001",
        email: "aaravsharma.student@skillsync.com",
        attendance: 92,
        performance: 88,
        risk: "Low",
        avatar: "A",
        avatarColor: "#6366f1",
        subjects: [
            { name: "Mathematics", marks: 91, total: 100 },
            { name: "Data Structures", marks: 87, total: 100 },
            { name: "DBMS", marks: 85, total: 100 },
            { name: "Networks", marks: 90, total: 100 },
            { name: "OS", marks: 78, total: 100 },
        ],
        weeklyTrend: [
            { week: "W1", score: 78 },
            { week: "W2", score: 82 },
            { week: "W3", score: 85 },
            { week: "W4", score: 88 },
            { week: "W5", score: 86 },
            { week: "W6", score: 88 },
        ],
        weakSubjects: ["OS"],
        skillGaps: ["Cloud Computing", "DevOps"],
        suggestions: [
            "Focus on Operating Systems concepts, especially memory management and scheduling algorithms.",
            "Enroll in the cloud computing module to close the identified skill gap.",
            "Maintain consistent attendance to sustain current performance trajectory.",
        ],
    },
    {
        id: "s2",
        name: "Priya Mehta",
        roll: "CSE002",
        email: "priyamehta.student@skillsync.com",
        attendance: 78,
        performance: 62,
        risk: "Medium",
        avatar: "P",
        avatarColor: "#a855f7",
        subjects: [
            { name: "Mathematics", marks: 55, total: 100 },
            { name: "Data Structures", marks: 60, total: 100 },
            { name: "DBMS", marks: 72, total: 100 },
            { name: "Networks", marks: 58, total: 100 },
            { name: "OS", marks: 65, total: 100 },
        ],
        weeklyTrend: [
            { week: "W1", score: 55 },
            { week: "W2", score: 58 },
            { week: "W3", score: 60 },
            { week: "W4", score: 62 },
            { week: "W5", score: 60 },
            { week: "W6", score: 62 },
        ],
        weakSubjects: ["Mathematics", "Networks"],
        skillGaps: ["Python", "Algorithms", "Problem Solving"],
        suggestions: [
            "Attend Mathematics tutorial sessions — 3 days per week recommended.",
            "Practice Network fundamentals via lab simulations.",
            "Complete AI-recommended Python beginner track to bridge coding skill gap.",
        ],
    },
    {
        id: "s3",
        name: "Rohan Das",
        roll: "CSE003",
        email: "rohandas.student@skillsync.com",
        attendance: 55,
        performance: 41,
        risk: "High",
        avatar: "R",
        avatarColor: "#ef4444",
        subjects: [
            { name: "Mathematics", marks: 38, total: 100 },
            { name: "Data Structures", marks: 42, total: 100 },
            { name: "DBMS", marks: 45, total: 100 },
            { name: "Networks", marks: 40, total: 100 },
            { name: "OS", marks: 38, total: 100 },
        ],
        weeklyTrend: [
            { week: "W1", score: 45 },
            { week: "W2", score: 43 },
            { week: "W3", score: 40 },
            { week: "W4", score: 42 },
            { week: "W5", score: 38 },
            { week: "W6", score: 41 },
        ],
        weakSubjects: ["Mathematics", "OS", "Networks"],
        skillGaps: ["All Core Subjects", "Logical Thinking", "Time Management"],
        suggestions: [
            "🚨 Immediate intervention required — schedule one-on-one counseling session.",
            "Provide a structured study plan covering all core subjects.",
            "Assign a peer mentor from the top 10% cohort.",
            "Consider extra lab sessions to reinforce conceptual understanding.",
        ],
    },
    {
        id: "s4",
        name: "Sneha Iyer",
        roll: "CSE004",
        email: "snehaiyer.student@skillsync.com",
        attendance: 95,
        performance: 94,
        risk: "Low",
        avatar: "S",
        avatarColor: "#10b981",
        subjects: [
            { name: "Mathematics", marks: 97, total: 100 },
            { name: "Data Structures", marks: 94, total: 100 },
            { name: "DBMS", marks: 92, total: 100 },
            { name: "Networks", marks: 95, total: 100 },
            { name: "OS", marks: 92, total: 100 },
        ],
        weeklyTrend: [
            { week: "W1", score: 88 },
            { week: "W2", score: 90 },
            { week: "W3", score: 92 },
            { week: "W4", score: 93 },
            { week: "W5", score: 95 },
            { week: "W6", score: 94 },
        ],
        weakSubjects: [],
        skillGaps: ["Advanced AI/ML"],
        suggestions: [
            "Exceptional performer — encourage participation in national-level coding competitions.",
            "AI recommends enrolling in the Advanced AI/ML elective for further growth.",
            "Mentor junior students to reinforce and deepen own knowledge.",
        ],
    },
    {
        id: "s5",
        name: "Kiran Patel",
        roll: "CSE005",
        email: "kiranpatel.student@skillsync.com",
        attendance: 70,
        performance: 55,
        risk: "Medium",
        avatar: "K",
        avatarColor: "#f59e0b",
        subjects: [
            { name: "Mathematics", marks: 60, total: 100 },
            { name: "Data Structures", marks: 50, total: 100 },
            { name: "DBMS", marks: 58, total: 100 },
            { name: "Networks", marks: 52, total: 100 },
            { name: "OS", marks: 55, total: 100 },
        ],
        weeklyTrend: [
            { week: "W1", score: 52 },
            { week: "W2", score: 54 },
            { week: "W3", score: 55 },
            { week: "W4", score: 53 },
            { week: "W5", score: 56 },
            { week: "W6", score: 55 },
        ],
        weakSubjects: ["Data Structures", "Networks"],
        skillGaps: ["System Design", "SQL Optimization"],
        suggestions: [
            "Revise linked lists, trees, and graph algorithms for Data Structures.",
            "Practice SQL optimization exercises — 30 min daily is recommended.",
            "Improve attendance — currently at risk threshold.",
        ],
    },
    {
        id: "s6",
        name: "Divya Nair",
        roll: "CSE006",
        email: "divyanair.student@skillsync.com",
        attendance: 88,
        performance: 79,
        risk: "Low",
        avatar: "D",
        avatarColor: "#f472b6",
        subjects: [
            { name: "Mathematics", marks: 80, total: 100 },
            { name: "Data Structures", marks: 78, total: 100 },
            { name: "DBMS", marks: 83, total: 100 },
            { name: "Networks", marks: 75, total: 100 },
            { name: "OS", marks: 80, total: 100 },
        ],
        weeklyTrend: [
            { week: "W1", score: 72 },
            { week: "W2", score: 74 },
            { week: "W3", score: 76 },
            { week: "W4", score: 78 },
            { week: "W5", score: 80 },
            { week: "W6", score: 79 },
        ],
        weakSubjects: ["Networks"],
        skillGaps: ["Cloud Architecture", "Docker"],
        suggestions: [
            "Networks is slightly weak — revisit OSI model and TCP/IP layers.",
            "Explore Docker and containerization to bridge DevOps skill gap.",
            "Consistent improvement trend — keep up the momentum!",
        ],
    },
];

export type Student = typeof STUDENTS[number];
